CREATE DATABASE LOJA_CHOCOLICIA;

CREATE TABLE STATES (
STATE_UID INT PRIMARY KEY,
STATES_UF VARCHAR (20),
STATE VARCHAR(25)
);


CREATE TABLE CITIES (
CITY_UID INT PRIMARY KEY,
STATE_UID INT,
CITY_NAME VARCHAR (40),
CONSTRAINT FK_CHAVE0 FOREIGN KEY (STATE_UID) REFERENCES STATES (STATE_UID)
);


CREATE TABLE CLIENT (
CLIENT_UID NUMBER(38, 0)  PRIMARY KEY,
NAME VARCHAR(40) NOT NULL,
DATE_BIRTH DATE NOT NULL,
REGISTRATION_DATE DATETIME,
CPF VARCHAR (11) NOT NULL,
MARITAL_STATUS VARCHAR(13) NOT NULL CHECK (MARITAL_STATUS IN ('SINGLE','MARRIED','WIDOWED','DIVORCED')),
GENDER VARCHAR(1) NOT NULL CHECK (SEXO IN ('F','M')) ,
ADDRESS_UID NUMBER(38, 0) NOT NULL,
EMAIL VARCHAR(40),
TELEPHONE_NUMBER VARCHAR (11)NOT NULL,
STATUS_CLIENT CHAR(1) DEFAULT('A') CHECK (STATUS_CLI IN ('A','I')),
CREATE_DT TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
CONSTRAINT "UNIQUE_KEYS" UNIQUE (CLIENT_UID, ADDRESS_UID),
CONSTRAINT "FK_CHAVE1" FOREIGN KEY (ADDRESS_UID) REFERENCES GENERAL_ADDRESS (ADDRESS_UID)
);

CREATE TABLE GENERAL_ADDRESS(
ADDRESS_UID NUMBER (38, 0) PRIMARY KEY,
ADDRESS_NAME VARCHAR(50) NOT NULL,
NUMBER_HOUSE VARCHAR(4) NOT NULL,
COMPLEMENT VARCHAR(40),
ZIP_CODE VARCHAR (8) NOT NULL,
DISTRICT VARCHAR (20) NOT NULL,
CITY_UID INT,
STATE_UID INT,
CONSTRAINT "UNIQUE_KEYS" UNIQUE (ADDRESS_UID)
CONSTRAINT "FK_CHAVE1" FOREIGN KEY (CITY_UID) REFERENCES CITIES (CITY_UID),
CONSTRAINT "FK_CHAVE2" FOREIGN KEY (STATE_UID) REFERENCES STATES (STATE_UID)

)

CREATE TABLE PROVIDER(
PROVIDER_UID NUMBER (38, 0) PRIMARY KEY,
COMPANY_NAME VARCHAR (20) NOT NULL,
SOCIAL_REASON VARCHAR (40) NOT NULL, -- 40
CNPJ VARCHAR (14), -- TAMANHO 14
COMPANY_WEBSITE VARCHAR(50) NULL,
ADDRESS_UID NUMBER(38, 0) NOT NULL,
EMAIL VARCHAR(40)NOT NULL,
TELEPHONE_NUMBER VARCHAR  (11)NOT NULL,
STATUS_PROVIDER CHAR(1) DEFAULT('A') CHECK (STATUS_FOR IN ('A','I')),
CREATE_DT TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
CONSTRAINT "UNIQUE_KEYS" UNIQUE (PROVIDER_UID, ADDRESS_UID),
CONSTRAINT "FK_CHAVE1" FOREIGN KEY (ADDRESS_UID) REFERENCES GENERAL_ADDRESS (ADDRESS_UID)
);


CREATE TABLE CONTACT_PROVIDER(
CONTACT_UID INT PRIMARY KEY,
PROVIDER_UID INT ,
NAME VARCHAR (40) NOT NULL,
GENDER VARCHAR(1) NOT NULL CHECK (SEXO IN ('F','M')) ,
FAX VARCHAR(10)  NULL,
CONTACT_EMAIL VARCHAR(40) NULL,
TELEPHONE_CONTACT VARCHAR(11) NOT NULL,
STATUS_CONTACT VARCHAR(1) DEFAULT('A') CHECK (STATUS_CONT IN ('A','I')),
CREATE_DT TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
CONSTRAINT FK_CHAVE5 FOREIGN KEY (CONTACT_UID) REFERENCES PROVIDER (PROVIDER_UID)
);

CREATE TABLE MARCA
(
COD_MARCA INT ,
NOME_MARCA VARCHAR(30) NOT NULL,
DATA_CADASTRO DATETIME,
STATUS_MARCA VARCHAR(1) DEFAULT('A') CHECK (STATUS_MARCA IN ('A','I')),
CONSTRAINT PK_COD_MARCA PRIMARY KEY (COD_MARCA)
);

CREATE TABLE CAD_PRODUTO
(
COD_PRODUTO INT  NOT NULL, -- CÓDI DO PRODUTO
COD_BARRA_PROD VARCHAR(13) NOT NULL,
COD_MARCA INT,
DATA_CADASTRO DATETIME,
DATA_VALIDADE DATETIME,
DESCRICAO_PROD VARCHAR (50) NOT NULL,
STATUS_PROD CHAR(1) DEFAULT 'A' NOT NULL CHECK(STATUS_PROD IN ('A','I')) ,
CONSTRAINT PK_COD_PROD PRIMARY KEY (COD_PRODUTO),
CONSTRAINT FK_CHAVE54 FOREIGN KEY (COD_MARCA) REFERENCES MARCA (COD_MARCA)
);

CREATE TABLE ESTOQUE(
COD_ESTOQUE INT, -- CÓDI DO ESTOQUE
COD_PROD INT NOT NULL, -- CÓDI DO PRODUTO
ESTOQUE_MAX INT NOT NULL, -- ESTOQUE MÁXIMO
ESTOQUE_MIN INT NOT NULL, -- ESTOQUE MINIMO
ESTOQUE_ATUAL INT DEFAULT(0), -- ESTOQUE ATUAL
SABOR VARCHAR(50), -- CARACTERÍSTICA
UNIDADE VARCHAR(10), -- UNIDADE DO PRODUTO (L LITRO, P PACOTE, U UNIDADE, G GRAMAS)
VL_VENDA_PROD DECIMAL(15,2) NOT NULL, -- VALOR DE VENDA DO PRODUTO
CONSTRAINT PK_COD_ESTOQUE PRIMARY KEY(COD_PROD,COD_ESTOQUE),
CONSTRAINT FK_CHAVE8 FOREIGN KEY (COD_PROD) REFERENCES CAD_PRODUTO (COD_PRODUTO)
);

CREATE TABLE ESTOQUE_FOR(
CODESTOQUE INT,
COD_FORNECEDOR INT,
COD_PRODUTO INT,
CONSTRAINT PK PRIMARY KEY (CODESTOQUE,COD_FORNECEDOR,COD_PRODUTO),
CONSTRAINT FK_CHAVE7 FOREIGN KEY (COD_PRODUTO,CODESTOQUE) REFERENCES ESTOQUE (COD_PROD,COD_ESTOQUE),
CONSTRAINT F_CHAVE7 FOREIGN KEY (COD_FORNECEDOR) REFERENCES  FORNECEDOR(COD_EMPRESA)
);

CREATE TABLE DEPARTAMENTO(
COD_DEPARTAMENTO INT PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR(40) NOT NULL,
DATA_CADASTRO  DATETIME ,
STATUS_DEP VARCHAR(1)  DEFAULT('A') CHECK (STATUS_DEP IN ('A','I'))
);

CREATE TABLE CADASTRO_FUNCIONARIO(
CODI_DO_FUNCIONARIO INT PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
CPF VARCHAR (12) NOT NULL,
RG VARCHAR (12) NOT NULL,
ENDERECO VARCHAR (40) NOT NULL,
NUMERO VARCHAR (5) NULL,
COMPLEMENTO VARCHAR (50) NULL,
CEP VARCHAR(8) NOT NULL,
BAIRRO VARCHAR (20) NOT NULL,
CODI_DEPARTAMENTO INT NOT NULL,
TURNO_FUNCI CHAR(1) NOT NULL CHECK(TURNO_FUNCI IN('M', 'T')) ,-- TURNO DO FUNCIONÁRIO
E_MAIL VARCHAR (40) NULL,
NIVEL_DE_ENSINO VARCHAR(12)  NOT NULL CHECK (NIVEL_DE_ENSINO IN ('FUNDAMENTAL','MEDIO ','TÉCNICO','SUPERIOR')),
SEXO VARCHAR(1) NOT NULL CHECK (SEXO IN ('F','M')) ,
DATA_DE_NASCIMENTO DATE NOT NULL,
ESTADO_CIVIL VARCHAR(14) NOT NULL CHECK (ESTADO_CIVIL IN ('SOLTEIRO(A)','CASADO(A)','VIUVO(A)','DIVORCIADO(A)')) ,
NUMERO_TEL VARCHAR (10)NOT NULL,
STATUS_FUNC VARCHAR(1)DEFAULT('A') CHECK (STATUS_FUNC IN ('A','I')),
CODCIDADE INT,
CODESTADO INT,
DATA_CADASTRO DATETIME,
CONSTRAINT FK_CHAVE9 FOREIGN KEY (CODCIDADE) REFERENCES CIDADES_TBL (CODCIDADE),
CONSTRAINT FK_CHAVE10 FOREIGN KEY (CODESTADO) REFERENCES ESTADOS_TBL (CODESTADO),
CONSTRAINT FK_CHAVE11 FOREIGN KEY (CODI_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
);

CREATE TABLE PAGAMENTO_FUNC(
CODI_PAG INT PRIMARY KEY,
COD_FUNC INT,
VALOR INT,
DATA DATE,
SITUACAO VARCHAR(40),
CONSTRAINT FK_CHAVE12 FOREIGN KEY (COD_FUNC) REFERENCES CADASTRO_FUNCIONARIO(CODI_DO_FUNCIONARIO)
);


CREATE TABLE CONTAS_PAGAR(
CODI_CONTA INT,
DESCRICAO_CONTA VARCHAR (30) NOT NULL,
RESPONSAVEL VARCHAR (20) NOT NULL,
DATA_DE_PAGAMENTO DATE NOT NULL, 
DATA_DE_VENCIMENTO DATE NOT NULL, 
VALOR_DA_CONTA DOUBLE NOT NULL,
VALOR_PA DOUBLE,
STATSPAG CHAR(2) DEFAULT('PE') NOT NULL CHECK(STATSPAG IN('PA','PE','AT')) ,-- STATUS DE PAGAMENTO(PA, PENDENTE OU ATRASADO)
STATUS_CONT CHAR(1) DEFAULT ('A') CHECK (STATUS_CONT IN ('A','I')) ,
CONSTRAINT PK_CON PRIMARY KEY (CODI_CONTA)
);

CREATE TABLE VENDAS(
CODI_VENDA INT   PRIMARY KEY NOT NULL,
CODI_DO_FUNCIONARIO INT NOT NULL,
CODI_DO_CLIENTE INT NOT NULL,
DATA_VENDA DATETIME DEFAULT (GETDATE()),
VALOR_FINAL DOUBLE NOT NULL, 
STATUS_VENDA VARCHAR(1)DEFAULT('A') CHECK (STATUS_VENDA IN ('A','F')),
CONSTRAINT FK_CHAVE14 FOREIGN KEY (CODI_DO_FUNCIONARIO) REFERENCES CADASTRO_FUNCIONARIO (CODI_DO_FUNCIONARIO),
CONSTRAINT FK_CHAVE15 FOREIGN KEY (CODI_DO_CLIENTE) REFERENCES CADASTRO_CLIENTE (CODI_DO_CLIENTE)
);


CREATE TABLE FORMA_PAG
(
COD_FORMPAG INT ,
TIPO_FORMPAG VARCHAR(8) NOT NULL,
CONSTRAINT PK_COD_FORMPAG PRIMARY KEY (COD_FORMPAG)
);

CREATE TABLE RECEBIMENTO
(
COD_RECEB INT NOT NULL, -- CÓDI DO RECEBIMENTO
COD_VENDA INT NOT NULL, -- CÓDI DA VENDA
CODFORMA_PAG INT NOT NULL, -- CÓDI DA FORMA PAGAMENTO
DATARECEB DATETIME NULL, -- DATA DE RECEBIMENTO
VALORRECEB DECIMAL(15,2) NOT NULL, -- VALOR RECEBIDO
STATUS_PAG CHAR(2) NOT NULL CHECK(STATUS_PAG IN('PA','PE','AT')), -- STATUS DO PAGAMENTO, PA(PA) PE(PENDENTE) AT(ATRASADO)
SATATUS_RECEBIMENTO CHAR(1) DEFAULT 'A' NOT NULL CHECK(SATATUS_RECEBIMENTO IN ('A','I')), -- STATUS DO PAGAMENTO(ATIVO OU INATIVO)
CONSTRAINT PK_CODRECEBVENDA PRIMARY KEY (COD_RECEB,COD_VENDA),
CONSTRAINT FK_VENDARECEB FOREIGN KEY (COD_VENDA) REFERENCES VENDAS (CODI_VENDA),
CONSTRAINT FK_FORMAPAGRECEB FOREIGN KEY (CODFORMA_PAG) REFERENCES FORMA_PAG (COD_FORMPAG)
);

CREATE TABLE DETALHES_VENDA(
CODI_VENDA INT  NOT NULL,
CODI_DO_DETALHE INT NOT NULL,
CODI_DO_PRODUTO INT NOT NULL,
COD_ESTOQUE INT,
QUANTIDADE INT NOT NULL,
VALOR_UNITÁRIO DOUBLE NOT NULL,
STATUS_ITEM_VENDA CHAR(1)DEFAULT 'A' NOT NULL CHECK(STATUS_ITEM_VENDA IN ('A','I')) ,
CONSTRAINT PK_DETALHE PRIMARY KEY (CODI_VENDA,CODI_DO_DETALHE), 
CONSTRAINT FK_CHAVE16 FOREIGN KEY (CODI_VENDA) REFERENCES VENDAS (CODI_VENDA),
CONSTRAINT FK_CHAVE17 FOREIGN KEY (CODI_DO_PRODUTO,COD_ESTOQUE) REFERENCES ESTOQUE (COD_PROD,COD_ESTOQUE)
);

CREATE TABLE CAD_LOGIN(
COD_FUN INT NOT NULL,
CAD_LOGIN VARCHAR (20)NOT NULL, 
SENHA VARCHAR (20) NOT NULL,
DATA_CADASTRO DATETIME,
NIVEL  VARCHAR(15)DEFAULT('2') CHECK (NIVEL IN ('1','2')),
STATUS_LOG VARCHAR(1)DEFAULT('A') CHECK (STATUS_LOG IN ('A','I')),
CONSTRAINT FK_CHAVE19 FOREIGN KEY (COD_FUN) REFERENCES CADASTRO_FUNCIONARIO (CODI_DO_FUNCIONARIO)
);

CREATE TABLE COMPRA (
COD_COMPRA INT  PRIMARY KEY,-- CÓDI DA COMPRA
COD_FORNE INT NOT NULL, -- CÓDI DO FORNECEDOR
VL_COMPRA DOUBLE NOT NULL,-- VALOR DA COMPRA
DATA_COMPRA DATETIME DEFAULT(GETDATE()) NOT NULL,-- DATA DE COMPRA
STATUS_COM CHAR(1) CHECK(STATUS_COM IN ('A','I')), -- STATUS DA COMPRA(ATIVO OU INATIVO)
CONSTRAINT FK_COD_FORNE FOREIGN KEY(COD_FORNE) REFERENCES FORNECEDOR(COD_EMPRESA)
);

CREATE TABLE ITEM_COMPRA(
COD_ITEM_COMPRA INT, -- CÓDI DO ITEM COMPRA
COD_COMPRA INT NOT NULL, -- CÓDI DA COMPRA
COD_PROD INT NOT NULL, -- CÓDI DO PRODUTO
COD_ESTOQUE INT NOT NULL, -- CÓDI DO ESTOQUE
QTD_PROD INT NOT NULL, -- QUANTIDADE DO PRODUTO
VL_UNITARIO DOUBLE NOT NULL, -- VALOR UNITÁRIO DO PRODUTO
UNIDADE VARCHAR(10) NOT NULL,-- UNIDADE DO PRODUTO (L LITRO, P PACOTE, U UNIDADE, G GRAMAS)
STATUS_ITEM_COM CHAR(1) CHECK(STATUS_ITEM_COM IN ('A','I')), -- STATUS DO ITEM(ATIVO OU INATIVO)
CONSTRAINT PK_COD_ITEM_COMPRA PRIMARY KEY(COD_ITEM_COMPRA, COD_COMPRA),
CONSTRAINT FK_COD_COMPRA FOREIGN KEY(COD_COMPRA) REFERENCES COMPRA(COD_COMPRA),
CONSTRAINT FK_COD_PROD FOREIGN KEY (COD_PROD) REFERENCES CAD_PRODUTO (COD_PRODUTO)
);

CREATE TABLE FALE_CONOSCO2 (
COD_FALE INT ,
NOME VARCHAR(40),
EMAIL VARCHAR(40),
DESCRICAO VARCHAR(2048)
);